version: '3.7'

services:
  redis:
    image: redis:5-alpine
    container_name: nabz-cache
    ports:
      - 6379:6379
    expose:
      - 6379
  mongo: 
    image: mongo:4.1.11-bionic
    container_name: nabz-mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-data/nabz:/var/lib/mongodb

  api:
    build: ./api
    container_name: nabz-api
    volumes:
      - ./api:/var/www/app
    ports:
      - 3001:3000
    links:
      - redis
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=nabz-cache
      - MONGO_HOST=nabz-mongo
      - MONGO_DB_NAME=nabz-sites
  # ui:
  #   build: ./ui
  #   container_name: nabz-ui
  #   volumes:
  #     - ./ui:/var/www/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000